---
# handlers file for Haproxy
- name: Starting service nginx
  service:
   name: nginx
   state: restarted

- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes
