---
# tasks file for  Haproxy
- name: Update & upgrade apt cache
  apt:
    update_cache: yes
    upgrade: full

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

- name: Add apt repositories into source list
  apt_repository:
    repo: ppa:vbernat/haproxy-2.4
  when: "'head' in group_names" 

- name: Update apt cache
  apt:
    update_cache: yes
  
- name: Download haproxy package
  apt:
    name: haproxy=2.4.18-0ubuntu1
    state: present
  when: "'head' in group_names" 
    
- name: Copy the HAProxy config file to remote system
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  when: "'head' in group_names" 

- name: Start service
  service:
    name: "haproxy"
    state: restarted
  when: "'head' in group_names" 


- name: Webserver installation
  apt:
   name: nginx
   state: present
  notify: Starting service nginx
  when: "'Backend' in group_names" 

- name: Updating content
  template:
   src: index.nginx-debian.html.j2
   dest: /var/www/html/index.nginx-debian.html
  when: "'Backend' in group_names" 

- name: Start service
  service:
    name: "nginx"
    state: restarted
  when: "'Backend' in group_names" 

- name: update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: "'Monitor' in group_names"

- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus
  when: "'Monitor' in group_names"


- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: restart_prometheus
  when: "'Monitor' in group_names"


- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
  when: "'Monitor' in group_names"



- name: install gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: "'Monitor' in group_names"


- name: add gpg hey
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no
  when: "'Monitor' in group_names"


- name: add repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no
  when: "'Monitor' in group_names"


- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: "'Monitor' in group_names"


- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  when: "'Monitor' in group_names"


- name: wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1
  when: "'Monitor' in group_names"
